name: olanma
description: Olanma goes to Church app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_native_splash: ^2.3.1
  responsive_sizer: ^3.1.1
  location: ^5.0.1
  google_maps_flutter: ^2.3.1
  flutter_polyline_points: ^1.0.0
  get: ^4.6.5
  syncfusion_flutter_calendar: ^22.2.7
  provider: ^6.0.5
  firebase_core: ^2.15.0
  intl: ^0.18.1

dependency_overrides:
  location_platform_interface: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/img/ola-icon.jpeg"
  android: "launcher_icon"
  ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/img/olaola.png
  color_dark: "#FFFFFF"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
